config/routes.rb
Rails.application.routes.draw do
  get 'test/index'

  root 'home#index'
  resources :citas
  resources :pacientes
  resources :test
  devise_for :usuarios
end

app/models/cita.rb
class Cita < ActiveRecord::Base
	belongs_to :paciente
	validates :paciente_id, :fecha, :hora_inicial, :hora_final, presence: true
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_many :citas
	validates :nombre, presence: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/citas_controller.rb
class CitasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_cita, only: [:show, :edit, :update, :destroy]
  before_action :get_catalogos, only: [:new, :edit, :create]

  respond_to :html

  # GET /citas
  # GET /citas.json
  def index
    @citas = Cita.all
  end

  # GET /citas/1
  # GET /citas/1.json
  def show
  end

  # GET /citas/new
  def new
    @cita = Cita.new
  end

  # GET /citas/1/edit
  def edit
  end

  # POST /citas
  # POST /citas.json
  def create
    @cita = Cita.new(cita_params)
    
    respond_to do |format|
      if @cita.save
        format.html { redirect_to @cita, notice: 'Cita was successfully created.' }
        format.json { render :show, status: :created, location: @cita }
      else
        format.html { render :new }
        format.json { render json: @cita.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citas/1
  # PATCH/PUT /citas/1.json
  def update
    respond_to do |format|
      if @cita.update(cita_params)
        format.html { redirect_to @cita, notice: 'Cita was successfully updated.' }
        format.json { render :show, status: :ok, location: @cita }
      else
        format.html { render :edit }
        format.json { render json: @cita.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citas/1
  # DELETE /citas/1.json
  def destroy
    @cita.destroy
    respond_to do |format|
      format.html { redirect_to citas_url, notice: 'Cita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cita
      @cita = Cita.find(params[:id])
    end

    def get_catalogos
      @pacientes = Paciente.select(:id, :nombre).all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cita_params
      params.require(:cita).permit(:paciente_id, :fecha, :hora_inicial, :hora_final, :descripcion)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  def test

  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nombre, :correo_electronico, :edad)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citas_helper.rb
module CitasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/citas/_form.html.erb
<%= form_for @cita, :html => { :class => "form-horizontal cita" } do |f| %>

    <% if @cita.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cita.errors.count, "error") %> prohibited this cita from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cita.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :paciente_id, :class => 'control-label col-md-2' %>
    <div class="controls col-md-4">
      <%= f.collection_select :paciente_id, @pacientes, :id, :nombre, {:prompt => "-- Seleccionar --"}, {:class => 'form-control'} %>
    </div>
    <%= error_span(@cita[:paciente_id]) %>
  </div>

  <div class="form-group">
    <%= f.label :fecha, :class => 'control-label col-md-2' %>
    <div class="controls  col-md-4">
      <%= f.text_field :fecha, :class => 'form-control' %>
    </div>
    <%= error_span(@cita[:fecha]) %>
  </div>
  <div class="form-group">
    <%= f.label :hora_inicial, :class => 'control-label col-md-2' %>
    <div class="controls  col-md-4">
      <%= f.text_field :hora_inicial, :class => 'form-control' %>
    </div>
    <%= error_span(@cita[:hora_inicial]) %>
  </div>
  <div class="form-group">
    <%= f.label :hora_final, :class => 'control-label col-md-2' %>
    <div class="controls  col-md-4">
      <%= f.text_field :hora_final, :class => 'form-control' %>
    </div>
    <%= error_span(@cita[:hora_final]) %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, :class => 'control-label col-md-2' %>
    <div class="controls  col-md-4">
      <%= f.text_area :descripcion, :class => 'form-control' %>
    </div>
    <%= error_span(@cita[:descripcion]) %>
  </div>

  <div class="form-group">
    <div class="controls  col-md-4 col-md-offset-2">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            citas_path, :class => 'btn btn-default' %>
    </div>
  </div>


<% end %>

app/views/citas/edit.html.erb
<%- model_class = Cita -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/citas/index.html.erb
<%- model_class = Cita -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:paciente_id) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:hora_inicial) %></th>
      <th class="hidden-xs"><%= model_class.human_attribute_name(:hora_final) %></th>
      <th class="hidden-xs visible-sm"><%= model_class.human_attribute_name(:descripcion) %></th>
      <th class="hidden-xs"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @citas.each do |cita| %>
      <tr>
        <td><%= link_to cita.paciente.nombre, cita_path(cita) %></td>
        <td><%= cita.fecha %></td>
        <td><%= cita.hora_inicial.strftime("%I:%M %p")  %></td>
        <td class="hidden-xs"><%= cita.hora_final.strftime("%I:%M %p")  %></td>
        <td class="hidden-xs visible-sm"><%= cita.descripcion %></td>
        <td class="hidden-xs">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cita_path(cita), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cita_path(cita),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cita_path,
            :class => 'btn btn-primary' %>

app/views/citas/new.html.erb
<%- model_class = Cita -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/citas/show.html.erb
<%- model_class = Cita -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:paciente_id) %>:</strong></dt>
  <dd><%= @cita.paciente.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @cita.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_inicial) %>:</strong></dt>
  <dd><%= @cita.hora_inicial.strftime("%I:%M %p") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_final) %>:</strong></dt>
  <dd><%= @cita.hora_final.strftime("%I:%M %p") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @cita.descripcion %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              citas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cita_path(@cita), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cita_path(@cita),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
	<h1>Bienvenido</h1>
	<p>Consultorio Online es una plataforma con la cual podra llevar el control total de las citas agendadas, historial medico de sus pacientes, contizaciones y mucho mas!.</p>
	<p>
		<% if not usuario_signed_in? %>
		<%= link_to "Iniciar Sesion", new_usuario_session_path, class: "btn btn-lg btn-primary" %></p>
		<% end %>
	</div>


	<div class="container">
		<!-- Example row of columns -->
		<div class="row">
			<div class="col-md-4">
				<h2>Fácil de usar</h2>
				<p>Consultorio Online es intuitivo y sencillo de utilizar. Además, si tienes cualquier duda puedes ponerte en contacto y te responderemos a la breved.</p>
			</div>
			<div class="col-md-4">
				<h2>Desde cualquier lugar</h2>
				<p>El acceso al sistema puede ser desde cualquier computadora o teléfono móvil. Tu información siempre estará resguardada y segura.</p>
			</div>
			<div class="col-md-4">
				<h2>Ahorra tiempo y dinero</h2>
				<p>Vuelve más eficiente y organizado tu negocio. Lleva el control de las citas, pacientes e historial medico desde un mismo lugar.</p>
			</div>
		</div>

		<hr>

		<!-- FOOTER -->
		<footer>
			<p>&copy; <%= DateTime.now.year %> Company, Inc. &middot; <a href="#">Privacidad</a> &middot; <a href="#">Terminos y Condiciones</a></p>
		</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Consultorio" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Consultorio Online", root_path, :class => "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if usuario_signed_in? %>
              <li class="active"><%= link_to "Incio", root_path%></li>
              <li><%= link_to "Citas", citas_path %></li>
              <li><%= link_to "Pacientes", pacientes_path %></li>
              <% end %>
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if usuario_signed_in? %>
                <li><%= link_to current_usuario.email %></li>
                <li><%= link_to "Salir", destroy_usuario_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Iniciar Sesion", new_usuario_session_path %></li>
              <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
         <%= bootstrap_flash %>

          <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Consultorio" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pacientes/_form.html.erb
<%= form_for @paciente, :html => { :class => "form-horizontal paciente" } do |f| %>

    <% if @paciente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @paciente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div id="content">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#red" data-toggle="tab">Informacion General</a></li>
        <li><a href="#orange" data-toggle="tab">Direccion</a></li>
        <li><a href="#yellow" data-toggle="tab">Trabajo</a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="red">
 <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-md-2' %>
    <div class="controls col-md-4">
      <%= f.text_field :nombre, :class => 'form-control col-md-4' %>
    </div>
    <%= error_span(@paciente[:nombre]) %>
  </div>
  <div class="form-group">
    <%= f.label :correo_electronico, :class => 'control-label col-md-2' %>
    <div class="controls col-md-4">
      <%= f.text_field :correo_electronico, :class => 'form-control' %>
    </div>
    <%= error_span(@paciente[:correo_electronico]) %>
  </div>
  <div class="form-group">
    <%= f.label :edad, :class => 'control-label col-md-2' %>
    <div class="controls col-md-4">
      <%= f.text_field :edad, :class => 'form-control' %>
    </div>
    <%= error_span(@paciente[:edad]) %>
  </div>
        </div>
        <div class="tab-pane" id="orange">
          <div class="row">
            <div class="col-md-4 col-md-offset-4">
              <fieldset>

                <!-- Form Name -->
                <legend>Address Details</legend>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Line 1</label>
                  <div class="col-sm-10">
                    <input type="text" placeholder="Address Line 1" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Line 2</label>
                  <div class="col-sm-10">
                    <input type="text" placeholder="Address Line 2" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">City</label>
                  <div class="col-sm-10">
                    <input type="text" placeholder="City" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">State</label>
                  <div class="col-sm-4">
                    <input type="text" placeholder="State" class="form-control">
                  </div>

                  <label class="col-sm-2 control-label" for="textinput">Postcode</label>
                  <div class="col-sm-4">
                    <input type="text" placeholder="Post Code" class="form-control">
                  </div>
                </div>



                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Country</label>
                  <div class="col-sm-10">
                    <input type="text" placeholder="Country" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <div class="pull-right">
                      <button type="submit" class="btn btn-default">Cancel</button>
                      <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                  </div>
                </div>

              </fieldset>

            </div>
          </div>
        </div>
        <div class="tab-pane" id="yellow">
            <h1>Yellow</h1>
            <p>yellow yellow yellow yellow yellow</p>
        </div>
    </div>
</div>

 

  <div class="form-group">
    <div class="controls  col-md-4 col-md-offset-2">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            pacientes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<%- model_class = Paciente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pacientes/index.html.erb
<%- model_class = Paciente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th class="hidden-xs"><%= model_class.human_attribute_name(:correo_electronico) %></th>
      <th class="hidden-xs"><%= model_class.human_attribute_name(:edad) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= link_to paciente.nombre, paciente_path(paciente) %></td>
        <td class="hidden-xs"><%= paciente.correo_electronico %></td>
        <td class="hidden-xs"><%= paciente.edad %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_paciente_path(paciente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      paciente_path(paciente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_paciente_path,
            :class => 'btn btn-primary' %>

app/views/pacientes/new.html.erb
<%- model_class = Paciente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pacientes/show.html.erb
<%- model_class = Paciente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @paciente.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correo_electronico) %>:</strong></dt>
  <dd><%= @paciente.correo_electronico %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad) %>:</strong></dt>
  <dd><%= @paciente.edad %></dd>
</dl>

<% if @paciente.citas.count > 0%>

<h3>Citas (<%= @paciente.citas.count.to_s %>)</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:hora_inicial) %></th>
      <th><%= model_class.human_attribute_name(:hora_final) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @paciente.citas.each do |cita| %>
      <tr>
        <td><%= link_to cita.id, cita_path(cita) %></td>
        <td><%= cita.fecha %></td>
        <td><%= cita.hora_inicial.strftime("%I:%M %p")  %></td>
        <td><%= cita.hora_final.strftime("%I:%M %p")  %></td>
        <td><%= cita.descripcion %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cita_path(cita), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cita_path(cita),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pacientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_paciente_path(@paciente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              paciente_path(@paciente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>